### PR TITLE
Create fibonachi.nim

### PR DESCRIPTION
**Pull request by juancarlospaco**
Compile:

```
nim c -d:release --opt:speed --passL:-s --gc:markAndSweep fibonachi.nim
```

Run:

```
./fibonachi N
```
Where `N` is your command line argument integer number (without quotes).

No Arguments:
```
./fibonachi
```
it uses `38` as requested.

Needs [Nim installed with ChooseNim](https://nim-lang.org/install_unix.html "curl https://nim-lang.org/choosenim/init.sh -sSf | sh").
:cat:

### CODE REVIEW

**Comment by alexander-rykhlitskiy** [comment]
@juancarlospaco wow I didn't think somebody can find my repo :) Many thanks for your contribution :+1: 
Don't you mind to make it similar to other implementations and accept command line argument? And then calculate fibonachi for all the numbers before argument?

**Comment by juancarlospaco** [comment]
All feedback is implemented.
:smile_cat:

**Comment by alexander-rykhlitskiy** [comment]
Great results! It's 1.5x faster than c! How is that even possible?
Just few notes. 
1) All implementations in the repo return this `  if n <= 1: return n` https://en.wikipedia.org/wiki/Fibonacci_number
2) It should output like this 
```
0 - 0
1 - 1
2 - 1
```
And you can add this line to readme right before c
`0.65 | **nim**        | nim c -d:release --opt:speed --passL:-s --gc:markAndSweep fibonachi.nim | time ./fibonachi |`
It's really amazing!

**Comment by alexander-rykhlitskiy** [comment]
I've almost forgotten. Could you please use 38 as default if no arguments?

**Comment by alexander-rykhlitskiy** [comment]
@juancarlospaco If you're busy, it's fine I'll implement it myself, but later. Anyway thanks for letting me know about nim

**Comment by juancarlospaco** [comment]
All feedback is implemented again.
:cat2:

**Comment by alexander-rykhlitskiy** [comment]
great, thanks for your work

**Comment by juancarlospaco** [comment]
I removed the flto and fast math since the C version dont have it neither.

**Comment by juancarlospaco** [comment]
Added Nim to the README.
:joy_cat:

**Comment by alexander-rykhlitskiy** [comment]
https://en.wikipedia.org/wiki/Fibonacci_number
it should return 
```
0 - 0
1 - 1
2 - 1
``` 
instead of 
``` 
0-1
1-1
2-2
```
Please note values and spaces.
You can use `if n <= 1: return n` instead of `if n <= 1: return 1` for correct values.

**Comment by juancarlospaco** [comment]
Fixed, sorry I didnt notice the white spaces.

**Comment by alexander-rykhlitskiy** [comment]
It looks perfect now. I definitely need to write spec not to fix each space. Thanks

**Comment by alexander-rykhlitskiy** [comment]
@juancarlospaco  btw ` --passC:-march=native` doesn't seem to make any difference.
And in the end why nim is faster than c? Is there any article in the web explaining it?

**Comment by juancarlospaco** [comment]
`march=native` is Not on the README anyways. I also removed the flag as I said.

Theres a lot of documentation and articles, feel free to join Nim's online community and to get started:

- https://nim-lang.org/documentation.html
- https://nim-lang.org/docs/theindex.html
- https://nim-lang.org/docs/tut1.html

From there you can get into more specific topics that may interest you. :smiley:

**Pull request merged**
